praetorian-inc/praetorian-cli

praetorian_cli/handlers/add.py

Update help text for --key option to make it more clear which key is expected. 
Documentation update

Make the help text clearer on what the asset key is

---

praetorian_cli/handlers/delete.py

Fixes the client-side error that occurs when trying to grab the key value from the DELETE response body. The response body is not a map, and does not contain a key entry. The value is instead pulled from the function argument.
Bug Fix

Pull key from fn argument instead of from API response when deleting

---

praetorian_cli/handlers/test.py

Use the `__path__` property of the praetorian_cli.sdk.test module as root directory for running pytest. This method works for both PyPI and editable installations.
Issue: https://github.com/praetorian-inc/chariot-ui/issues/70
Bug fix
When the CLI is installed from PyPI, the tests won't run at all.

Fixed directory where the test py files are loaded from

---

praetorian_cli/handlers/link.py

Adds support for Azure Org-Level integrations by removing the subscription specifier. The entire tenant will now be enumerated, so specifying the subscription is not necessary.
New Feature

Azure Org-Level integration

---

README.md
praetorian_cli/handlers/cli_decorators.py

Previously, we can only import scripts in the praetorian_cli/scripts location. This means if a user wants to use their own scripts, they will need to place the scripts where the installed package is. If they don't want to tinker with the central location where the praetorian-cli package is installed, they can do a local editable installation using `pip install -e .`. Both are somewhat clumsy and prone to get tripped up by Python environment.
What I want to support out of the box is that someone can simply put their script anywhere and the `--script` option should work as expected. This should lower the barrier to use scripts because they don't need to deal with the pip packaging system.
The logic is as follows:
- First attempt to import it from the `.scripts` module. This will work for …

Added the ability to import script from any location

---

praetorian_cli/handlers/chariot.py
praetorian_cli/scripts/hello.py

The current plugins mechanism doesn't fit all workflows .e.g https://github.com/praetorian-inc/praetorian-cli/pull/30. It would be useful to allow plugins to register their own commands. 
It would allow engineers to automate common workflows, and store them in the scripts dir, to make them available via a CLI as opposed to making them create their own CLI on top of the SDK.

allow plugins to attach commands

---

praetorian_cli/handlers/add.py
praetorian_cli/handlers/cli_decorators.py
praetorian_cli/handlers/update.py
praetorian_cli/handlers/utils.py

When risks are first created, they are always in the Triage state, regardless of what the state is supplied in the CLI. 
This change limits the valid statuses to only those in "T" in the CLI for the `add risk` command.
Also, included minor changes to the other add and update commands to improve usability.

Limit statuses to triage for new risks; improve intuitiveness of the add and update commands

---

praetorian_cli/plugins/scripts/list_assets.py

If the asset isn't a root asset, we should early return
Bug fix

added an early return; I missed it in an earlier PR

---

praetorian_cli/handlers/add.py

Backend always treat new assets as seeds. So, removing this option.

remove the --seed option when adding asset

---

praetorian_cli/handlers/add.py
praetorian_cli/handlers/cli_decorators.py

- Fix a bug where the asset key had the wrong variable name.
- Added the class field to allow people to add non-weakness risks.
- Made the status field mandatory (picking up from where we left off with Marek's observation a couple of weeks ago)

Tweaks to the `add risk` command

---

README.md
praetorian_cli/handlers/add.py

Fixes the `add job` command
[Bug Fix] 
[(minor) Documentation update]
While variable renaming, asset option was not passed to the function causing failures when running the command.
Also `@cli-handler` decorator was missing which prevented context passing.

Fix asset key handling in add.py

---

praetorian_cli/handlers/add.py
praetorian_cli/handlers/cli_decorators.py
praetorian_cli/handlers/update.py
praetorian_cli/handlers/utils.py

The status field of assets has morphed to mostly mean the scan priority. This is to map the wording of the CLI parameter closer to the update in the UI that went in on 7/10. It will be a breaking change for people who use the `update asset` command.
Breaking change.

Adjusted asset status as 'priority'

---

praetorian_cli/sdk/chariot.py

Fixes - https://praetorianlabs.slack.com/archives/C06RDPMGZJS/p1720805556032759
Bug fix
Handles when proof of exploit is not a valid json.

Handle plain text poe content

---

praetorian_cli/plugins/commands/nessus_xml.py

Use a thread pool to upload risks and proofs instead of a new thread to have an element of request limiting.

Use thread pool for Nessus XML

---

praetorian_cli/handlers/list.py

Allow users to filter assets and risks by attributes on CLI
New Feature
Allow users to do advanced filtering with attributes. 
Now, to find all assets with a specific `source` attribute users can run the query - 
`praetorian chariot list assets -attr source xyz.com` 
In this version, you can filter on only a single attribute at a time.

Add filtering by attribute for assets and risks

---

praetorian_cli/handlers/add.py

The schema of attribute changed from class/name pair to name/value pair as of 7/15. Updating the `add attribute` command to match that.

Updated the 'add attribute' command to use name/value pair

---

praetorian_cli/handlers/cli_decorators.py
praetorian_cli/handlers/list.py

List attributes by name, asset, or risk
New Feature
With attributes having a generic key string, a normal list attributes will end up with more than required entries, added an option to list attributes of a specific asset or risk for usability.

Add capability to list attributes by asset or risk

---

praetorian_cli/handlers/delete.py
praetorian_cli/handlers/utils.py
praetorian_cli/sdk/test/test_asset.py

We have changed to soft-delete in the backend for assets by setting the status. I will want to preserve the `delete asset` command, which reads the most natural to the end users of the CLI. The underlying implementation is updated to change the status, instead of calling DELETE /asset

Updated CLI to match the removal of DELETE /asset in the backend

---

README.md
docs/configure.md
praetorian_cli/cli.py
praetorian_cli/handlers/chariot.py
praetorian_cli/sdk/keychain.py

Add a configure command allowing users to create keychain files using their username and password
[New Feature]
Allows users to easily create a keychain file to be used for interacting with the CLI
Usage `praetorian configure`

Add configure command

---

praetorian_cli/handlers/configure.py
praetorian_cli/sdk/keychain.py

Reason for adding it is that we want all users, including the likes of Steve to never need to copy and edit the keychain file directly, including setting it up for their personal stack.

Added user_pool_id for the 'configure' command

---

praetorian_cli/handlers/get.py
praetorian_cli/sdk/chariot.py
praetorian_cli/sdk/test/test_files.py

Allow SDK users to get file content directly without file operations. 
[New Feature]
This keeps the original CLI behaviour intact and makes it easier for power users to get the file content into the program directly without expensive file IO.

Return file content when no path is specified.
