README.md
Added the steps for installing the CLI using the local directory method.
=> Update README to add local installation of the CLI for script development

praetorian_cli/handlers/link.py, praetorian_cli/sdk/chariot.py
Fixes https://github.com/praetorian-inc/chariot-ui/pull/69 by implementing https://github.com/praetorian-inc/chaos/pull/853. Parallel of https://github.com/praetorian-inc/chariot-ui/pull/69.
Bug Fix
=> Add integration identifiers (name, URL, ID, etc) as the account value instead of the integration field

praetorian_cli/handlers/delete.py
Fixes the delete command to work properly with the given endpoint
Bug Fix
The command is created in a for loop, but that erases context of the previous item. 
We need the command creation in a separate function outside of the loop.
=> Fix issues with delete command

praetorian_cli/handlers/add.py, praetorian_cli/handlers/update.py
Bug fix for update command
Bug Fix
The command was unable to process some of the arguments passed to it correctly. 
I have removed them in favor of more generic terms.
=> Fix issues with update command

CHANGELOG.md, setup.cfg
=> Version upgrade to 1.0.2

README.md
Small typo fix in an example
Bug fix
=> Fix typo on an example invocation

CHANGELOG.md, setup.cfg
=> Version upgrade

praetorian_cli/handlers/link.py
Adds gitlab integration to CLI
New Feature
=> Add gitlab integration

praetorian_cli/scripts/utils.py, praetorian_cli/scripts/validate-secrets.py
Common, useful functions for scripts. Starting with a requires() decorator that checks whether the system has
the required command installed.
Refactor
=> Utilities for scripts

praetorian_cli/handlers/add.py, praetorian_cli/handlers/delete.py
Adds create (and update, implicitly, as the request is idempotent) and delete for references. CLI implementation of https://github.com/praetorian-inc/chaos/pull/890.
New Feature
=> Add create/update/delete for references

praetorian_cli/scripts/reporting.py
Allow PS to frictionlessly leverage Chariot for reporting
=> Reporting workflow commit fix

praetorian_cli/handlers/cli_decorators.py
Improved the check whether a py file is a plugin script.
Improvement
=> Added a check for whether the process symbol is callable

praetorian_cli/handlers/plugin.py
Let's see whether calling these "plugin" is more natural.
=> Renamed the 'run' command group to 'plugin'

praetorian_cli/handlers/add.py, praetorian_cli/sdk/chariot.py
Specifies `class:manual` for regular uploads and `class:definition` for definition uploads.
New Feature
Implementation of https://github.com/praetorian-inc/chaos/pull/914
=> Specify class for manual uploads and definitions

README.md, praetorian_cli/plugins/README.md
Readme changes for using and extending the CLI with plugins
Documentation update.
=> Rewording Readme

CHANGELOG.md, setup.cfg
=> Version upgrade to 1.1

praetorian_cli/handlers/update.py, praetorian_cli/handlers/utils.py
This is no longer possible on the backend API. Removing it.
=> Remove the 'update job' command

praetorian_cli/handlers/plugin.py, praetorian_cli/plugins/commands/nessus.py
This is Rad's Nessus plugin. I recreated his PR because I changed the directory structure of the plugin mechanism quite drastically today. It is cleaner to recreate the PR so that the diffs are easy to see.
=> Nessus Integration

praetorian_cli/handlers/add.py, praetorian_cli/handlers/delete.py, praetorian_cli/handlers/get.py, praetorian_cli/handlers/list.py, praetorian_cli/handlers/utils.py
Remove references command as attributes now describes both assets and risks.
Breaking change
https://praetorianlabs.slack.com/archives/C06NH5TJL72/p1719848165666329
=> Remove references as a command

praetorian_cli/plugins/commands/nessus.py, praetorian_cli/sdk/chariot.py
Upload POE from Nessus plugin into Chariot
=> add poe from nessus plugin

praetorian_cli/plugins/commands/report.py, praetorian_cli/plugins/scripts/validate_secrets.py, praetorian_cli/plugins/utils.py
Some plugins require certain Python packages to be installed. This changes added a decorator to support that, similar to the original @requires decorator.
New feature
=> Added support for package prerequisite

praetorian_cli/sdk/chariot.py
Print the raw error message to help users of CLI self-help if their commands fail.
Improvement
=> Added error message from backend to the CLI error printout

praetorian_cli/plugins/commands/report.py, praetorian_cli/plugins/scripts/validate_secrets.py, praetorian_cli/plugins/utils.py
Reverts praetorian-inc/praetorian-cli#69
For third party commands, this works better ++ more flexible with help text.
=> Revert "Added support for package prerequisite"

praetorian_cli/handlers/list.py, praetorian_cli/plugins/commands/report.py
Split the list attribute command
Breaking Change
Attributes have changed in structure and combined for risks and assets, so now users can filter attributes by supplying the key of the asset or risk.
=> Specify we can filter attributes by key

praetorian_cli/plugins/scripts/list_assets.py
The key for attributes changed to have an additional `#asset#`.
Bug fix
=> Updated the indices for composing the asset keys

praetorian_cli/handlers/delete.py, praetorian_cli/sdk/chariot.py
Add a purge command to remove your account. 
`praetorian chariot purge` 
New Feature
=> Purge account

praetorian_cli/handlers/delete.py, praetorian_cli/sdk/chariot.py
Adding a delete file command
New Feature
=> Added commands for deleting files and purging account

README.md
Updated the documentation for how to authenticate to the CLI in SSO orgs
New feature
=> Updated with authentication methods for organization using SSO

praetorian_cli/handlers/add.py, praetorian_cli/sdk/chariot.py
The backend API has been updated to side-step the lambda function content size limit. Updating the CLI to match.
**Don't publish before this backend commit is deployed: https://github.com/praetorian-inc/chaos/commit/f0462411f35d9e61dbbc09f67975521bd8f193a6**
=> Updated file upload to an explicit two-step process

praetorian_cli/handlers/add.py, praetorian_cli/plugins/commands/nessus_api.py, praetorian_cli/plugins/commands/nessus_xml.py, praetorian_cli/plugins/commands/report.py, praetorian_cli/sdk/chariot.py, praetorian_cli/sdk/test/test_files.py
Remove usage of class parameter
Breaking change
=> Remove usage of class param

praetorian_cli/sdk/keychain.py
Cache token for authenticating all APIs within a session. 
Improvement
=> Cache authenticated token for a session

praetorian_cli/sdk/chariot.py
Add risk definition to the --details option
New Feature
=> include risk definition in details

CHANGELOG.md, setup.cfg
=> rev up to 1.2.1

CHANGELOG.md
=> Corrected a version typo

praetorian_cli/plugins/commands/nessus_api.py
Rate limit Nessus API uploading from the CLI with threadpool
=> Lower concurrency of the nessus-api command

praetorian_cli/handlers/list.py, praetorian_cli/plugins/scripts/list_assets.py
Command was failing due to incorrect parameter name
Bug Fix
=> Fix list asset command and script

CHANGELOG.md, praetorian_cli/sdk/test/__init__.py, setup.cfg
=> Version upgrade 1.2.2

setup.cfg
=> Upgrade to 1.2.3

praetorian_cli/sdk/chariot.py
Also simplified code around base64.
=> Switched webhook from PIN to UUID

praetorian_cli/plugins/commands/nessus_api.py, praetorian_cli/plugins/commands/nessus_xml.py
Set the source to 'nessus' now that backend has added the support
=> set source to 'nessus' for the Nessus command

praetorian_cli/cli.py, praetorian_cli/handlers/configure.py, praetorian_cli/sdk/keychain.py
Also refactored the configure command to its own file.
=> Fixed bug on clearing account; took Marek's suggestion for non-interactive supply of `configure` parameters

CHANGELOG.md, praetorian_cli/handlers/cli_decorators.py, praetorian_cli/handlers/configure.py, praetorian_cli/handlers/delete.py, praetorian_cli/handlers/get.py, praetorian_cli/handlers/list.py, praetorian_cli/handlers/test.py, praetorian_cli/sdk/test/models.py, praetorian_cli/sdk/test/test_cli.py, praetorian_cli/sdk/test/utils.py, pyproject.toml, setup.cfg
- Fixed regression bug on the `--plugin` option for a few `get` and `list` commands
- Added an initial regression test suite for the CLI itself.
- Rev'd up to 1.3.2.
=> Fix plugin option bug, CLI tests, and rev to 1.3.2

CHANGELOG.md, setup.cfg
=> Version upgrade 1.3.3

README.md, docs/plugin-development.md
- We only document plugin commands. 
- Removed reference to plugin scripts and static plugin commands.
=> Simplify the documentation on plugins

CHANGELOG.md, setup.cfg
=> Version upgrade 1.3.5

CHANGELOG.md, setup.cfg
=> Version upgrade 1.3.6

praetorian_cli/scripts/commands/nessus_api.py, praetorian_cli/scripts/commands/nessus_xml.py
Updating _upload to match backend changes
=> adjust poe upload path for nessus plugins
